name: Buf CI
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          # Don't push the schema to the Buf Schema Registry
          push: false
          # Optional GitHub token for API requests. Ensures requests aren't rate limited.
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # make sure the PR includes the updated generated code.
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Generate code"
        run: make generate
      - uses: CatChen/check-git-status-action@v1
        with:
          fail-if-not-clean: true
