name: Create release and publish packages

on:
  push:
    branches:
      - "releases/v*"

jobs:
  publish-packages:
    name: Publish Release Packages
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish packages
        uses: ./.github/actions/publish-packages
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          version_source: ${{ github.ref }}

  finalize-release:
    name: Finalize Release
    runs-on: ubuntu-latest

    needs:
      - publish-packages

    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tag Release
        run: |
          VERSION="${GITHUB_REF##*/}"  # from 'refs/heads/releases/v1.2.1' → 'v1.2.1'
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          git tag "$VERSION"
          git push origin tag "$VERSION"

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          commitish: ${{ github.ref }}
          tag: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
